title: "Sameet Krishna"
email: skris114@asu.edu
description: >- # this means to ignore newlines until "baseurl:"
  Software Developer. Hacking my way through life one project at a time.
baseurl: "/" 
url: "https://krishnasameeth.github.io/" 
twitter_username: krishna_sameeth
github_username:  krishnasameeth

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
